name: Deployment CI

on:
  push:
    branches:
      - chore/git-flow
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install packages
        run: npm install

      - name: build storybook
        run: npm run build:storybook

      - name: deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: aws s3 cp ./example s3://$S3_BUCKET \
          --acl public-read \
          --recursive \
          --region ap-northeast-2
